mad_libs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story_time.urls')),
]

story_time/urls.py
from . import views
from django.urls import path

app_name = 'story_time'
urlpatterns = [
    path('', views.home, name='home'),
    path('story_one_form/', views.story_one_form, name='story_one_form'),
    path('story_two_form/', views.story_two_form, name='story_two_form'),
    path('story_war_form/', views.story_war_form, name='story_war_form'),
    path('story_walmart_form/', views.story_walmart_form, name='story_walmart_form'),
    path('story_dragons_form/', views.story_dragons_form, name='story_dragons_form'),
    path('story_love_letter_form/', views.story_love_letter_form, name='story_love_letter_form'),
    path('story_smelly_cat_form/', views.story_smelly_cat_form, name='story_smelly_cat_form'),
    path('story_greeting_earthlings_form/', views.story_greeting_earthlings_form, name='story_greeting_earthlings_form'),
    path('hail_to_the_chief_form/', views.story_hail_to_the_chief_form, name='story_hail_to_the_chief_form'),
    path('story_holiday_festivities_form/', views.story_holiday_festivities_form, name='story_holiday_festivities_form'),
    path('story_pizza_parlor_form/', views.story_pizza_parlor_form, name='story_pizza_parlor_form'),
    path('story_cat_and_the_fiddle_form/', views.story_cat_and_the_fiddle_form, name='story_cat_and_the_fiddle_form'),
    path('storystory_baseball_form/', views.story_baseball_form, name='story_baseball_form'),
    path('story_JJRTolkien_form/', views.story_JJRTolkien_form, name='story_JJRTolkien_form'),
    path('story_jack_and_jill_form/', views.story_jack_and_jill_form, name='story_jack_and_jill_form'),
    path('story_one/<int:item_id>', views.story_one, name='story_one'),
    path('story_two/<int:item_id>', views.story_two, name='story_two'),
    path('story_war/<int:item_id>', views.story_war, name='story_war'),
    path('story_dragons/<int:item_id>', views.story_dragons, name='story_dragons'),
    path('story_walmart/<int:item_id>', views.story_walmart, name='story_walmart'),
    path('story_love_letter/<int:item_id>', views.story_love_letter, name='story_love_letter'),
    path('story_smelly_cat/<int:item_id>', views.story_smelly_cat, name='story_smelly_cat'),
    path('story_greeting_earthlings/<int:item_id>', views.story_greeting_earthlings, name='story_greeting_earthlings'),
    path('hail_to_the_chief/<int:item_id>', views.story_hail_to_the_chief, name='story_hail_to_the_chief'),
    path('story_holiday_festivities/<int:item_id>', views.story_holiday_festivities, name='story_holiday_festivities'),
    path('story_pizza_parlor/<int:item_id>', views.story_pizza_parlor, name='story_pizza_parlor'),
    path('story_cat_and_the_fiddle/<int:item_id>', views.story_cat_and_the_fiddle, name='story_cat_and_the_fiddle'),
    path('story_baseball/<int:item_id>', views.story_baseball, name='story_baseball'),
    path('story_JJRTolkien/<int:item_id>', views.story_JJRTolkien, name='story_JJRTolkien'),
    path('story_jack_and_jill/<int:item_id>', views.story_jack_and_jill, name='story_jack_and_jill'),
    path('all_stories', views.all_stories, name='all_stories'),
    # path('story_delete<int:item_id>/', views.story_delete, name='story_delete')
]

story_time/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import StoryOneForm, StoryTwoForm, StoryWarForm, StoryDragonsForm, StoryWalmartForm,\
    StoryLoveLetterForm, StorySmellyCatForm, StoryGreetingsEarthlingsForm, HailToTheChiefForm, HolidayFestivitiesForm,\
    PizzaParlorForm, PizzaParlor, CatAndTheFiddle, CatAndTheFiddleForm, Baseball, BaseballForm, JJRTolkien,\
    JJRTolkienForm, JackAndJill, JackAndJillForm
from .models import StoryOne, StoryTwo, StoryWar, StoryDragons, StoryWalmart, StoryLoveLetter,\
    StorySmellyCat, StoryGreetingsEarthlings, HailToTheChief, HolidayFestivities


# Create your views here.
def home(request):
    context = {}
    return render(request, 'story_time/home.html', context)


def story_one(request, item_id):
    item = StoryOne.objects.get(pk=item_id)
    context = {'item': item}
    return render(request, 'story_time/story_one.html', context)


def story_two(request, item_id):
    item = StoryTwo.objects.get(pk=item_id)
    context = {'item': item}
    return render(request, 'story_time/story_two.html', context)


def story_war(request, item_id):
    item = StoryWar.objects.get(pk=item_id)
    context = {'item': item}
    return render(request, 'story_time/story_war.html', context)


def story_dragons(request, item_id):
    item = StoryDragons.objects.get(pk=item_id)
    return render(request, 'story_time/story_dragons.html', {'item': item})


def story_walmart(request, item_id):
    item = StoryWalmart.objects.get(pk=item_id)
    return render(request, 'story_time/story_walmart.html', {'item': item})


def story_love_letter(request, item_id):
    item = StoryLoveLetter.objects.get(pk=item_id)
    return render(request, 'story_time/story_love_letter.html', {'item': item})


def story_smelly_cat(request, item_id):
    item = StorySmellyCat.objects.get(pk=item_id)
    return render(request, 'story_time/story_smelly_cat.html', {'item': item})


def story_greeting_earthlings(request, item_id):
    item = StoryGreetingsEarthlings.objects.get(pk=item_id)
    return render(request, 'story_time/story_greeting_earthlings.html', {'item': item})


def story_hail_to_the_chief(request, item_id):
    item = HailToTheChief.objects.get(pk=item_id)
    return render(request, 'story_time/story_hail_to_the_chief.html', {'item': item})


def story_holiday_festivities(request, item_id):
    item = HailToTheChief.objects.get(pk=item_id)
    return render(request, 'story_time/story_holiday_festivities.html', {'item': item})


def story_pizza_parlor(request, item_id):
    item = PizzaParlor.objects.get(pk=item_id)
    return render(request, 'story_time/story_pizza_parlor.html', {'item': item})


def story_cat_and_the_fiddle(request, item_id):
    item = CatAndTheFiddle.objects.get(pk=item_id)
    return render(request, 'story_time/story_cat_and_the_fiddle.html', {'item': item})


def story_baseball(request, item_id):
    item = Baseball.objects.get(pk=item_id)
    return render(request, 'story_time/story_baseball.html', {'item': item})


def story_JJRTolkien(request, item_id):
    item = Baseball.objects.get(pk=item_id)
    return render(request, 'story_time/story_JJRTolkien.html', {'item': item})


def story_jack_and_jill(request, item_id):
    item = JackAndJill.objects.get(pk=item_id)
    return render(request, 'story_time/story_jack_and_jill.html', {'item': item})


def story_one_form(request,):
    form = StoryOneForm(request.POST or None)

    if form.is_valid():
        form.save()
        story_list = StoryOne.objects.all()
        x = len(story_list)
        story = story_list[x-1]
        last_story = story.id
        item = StoryOne.objects.get(pk=last_story)
        context = {'item': item}
        return render(request, 'story_time/story_one.html', context)
    return render(request, 'story_time/story_form.html', {'form': form})


def story_two_form(request,):
    form = StoryTwoForm(request.POST or None)

    if form.is_valid():
        form.save()
        story_list = StoryTwo.objects.all()
        x = len(story_list)
        story = story_list[x-1]
        last_story = story.id
        item = StoryTwo.objects.get(pk=last_story)
        context = {'item': item}
        return render(request, 'story_time/story_two.html', context)
    return render(request, 'story_time/story_form.html', {'form': form})


def story_war_form(request,):
    form = StoryWarForm(request.POST or None)

    if form.is_valid():
        form.save()
        story_list = StoryWar.objects.all()
        x = len(story_list)
        story = story_list[x-1]
        last_story = story.id
        item = StoryWar.objects.get(pk=last_story)
        context = {'item': item}
        return render(request, 'story_time/story_war.html', context)
    return render(request, 'story_time/story_form.html', {'form': form})


def story_dragons_form(request):
    form = StoryDragonsForm(request.POST or None)

    if form.is_valid():
        form.save()
        story_list = StoryDragons.objects.all()
        x = len(story_list)
        story = story_list[x-1]
        last_story = story.id
        item = StoryDragons.objects.get(pk=last_story)
        context = {'item': item}
        return render(request, 'story_time/story_dragons.html', context)
    return render(request, 'story_time/story_form.html', {'form': form})


def story_walmart_form(request):
    form = StoryWalmartForm(request.POST or None)

    if form.is_valid():
        form.save()
        story_list = StoryWalmart.objects.all()
        x = len(story_list)
        story = story_list[x-1]
        last_story = story.id
        item = StoryWalmart.objects.get(pk=last_story)
        context = {'item': item}
        return render(request, 'story_time/story_walmart.html', context)
    return render(request, 'story_time/story_form.html', {'form': form})


def story_love_letter_form(request):
    form = StoryLoveLetterForm(request.POST or None)

    if form.is_valid():
        form.save()
        story_list = StoryLoveLetter.objects.all()
        x = len(story_list)
        story = story_list[x-1]
        last_story = story.id
        item = StoryLoveLetter.objects.get(pk=last_story)
        context = {'item': item}
        return render(request, 'story_time/story_love_letter.html', context)
    return render(request, 'story_time/story_form.html', {'form': form})


def story_smelly_cat_form(request):
    form = StorySmellyCatForm(request.POST or None)

    if form.is_valid():
        form.save()
        story_list = StorySmellyCat.objects.all()
        x = len(story_list)
        story = story_list[x-1]
        last_story = story.id
        item = StorySmellyCat.objects.get(pk=last_story)
        context = {'item': item}
        return render(request, 'story_time/story_smelly_cat.html', context)
    return render(request, 'story_time/story_form.html', {'form': form})


def story_greeting_earthlings_form(request):
    form = StoryGreetingsEarthlingsForm(request.POST or None)

    if form.is_valid():
        form.save()
        story_list = StoryGreetingsEarthlings.objects.all()
        x = len(story_list)
        story = story_list[x-1]
        last_story = story.id
        item = StoryGreetingsEarthlings.objects.get(pk=last_story)
        context = {'item': item}
        return render(request, 'story_time/story_greeting_earthlings.html', context)
    return render(request, 'story_time/story_form.html', {'form': form})


def story_hail_to_the_chief_form(request):
    form = HailToTheChiefForm(request.POST or None)

    if form.is_valid():
        form.save()
        story_list = HailToTheChief.objects.all()
        x = len(story_list)
        story = story_list[x-1]
        last_story = story.id
        item = HailToTheChief.objects.get(pk=last_story)
        context = {'item': item}
        return render(request, 'story_time/story_hail_to_the_chief.html', context)
    return render(request, 'story_time/story_form.html', {'form': form})


def story_holiday_festivities_form(request):
    form = HolidayFestivitiesForm(request.POST or None)

    if form.is_valid():
        form.save()
        story_list = HolidayFestivities.objects.all()
        x = len(story_list)
        story = story_list[x-1]
        last_story = story.id
        item = HolidayFestivities.objects.get(pk=last_story)
        context = {'item': item}
        return render(request, 'story_time/story_holiday_festivities.html', context)
    return render(request, 'story_time/story_form.html', {'form': form})


def story_pizza_parlor_form(request):
    form = PizzaParlorForm(request.POST or None)

    if form.is_valid():
        form.save()
        story_list = PizzaParlor.objects.all()
        x = len(story_list)
        story = story_list[x-1]
        last_story = story.id
        item = PizzaParlor.objects.get(pk=last_story)
        context = {'item': item}
        return render(request, 'story_time/story_pizza_parlor.html', context)
    return render(request, 'story_time/story_form.html', {'form': form})


def story_cat_and_the_fiddle_form(request):
    form = CatAndTheFiddleForm(request.POST or None)

    if form.is_valid():
        form.save()
        story_list = CatAndTheFiddle.objects.all()
        x = len(story_list)
        story = story_list[x-1]
        last_story = story.id
        item = CatAndTheFiddle.objects.get(pk=last_story)
        context = {'item': item}
        return render(request, 'story_time/story_cat_and_the_fiddle.html', context)
    return render(request, 'story_time/story_form.html', {'form': form})


def story_baseball_form(request):
    form = BaseballForm(request.POST or None)

    if form.is_valid():
        form.save()
        story_list = Baseball.objects.all()
        x = len(story_list)
        story = story_list[x-1]
        last_story = story.id
        item = Baseball.objects.get(pk=last_story)
        context = {'item': item}
        return render(request, 'story_time/story_baseball.html', context)

story_time/templates/story_time/all_stories.html
{% extends 'story_time/base.html' %}

{% block body %}
  <h1 class="text-center">Your Stories</h1>
  <div class="ml-3 mt-4">
  {% if story_list1 %}
  <h3>Be Kind Stories</h3>
    {% for story in story_list1 %}
      <a href="{% url 'story_time:story_one' story.id %}">{{ story.story_name }}</a><br>
    {% endfor %}
  {% endif %}
  {% if story_list2 %}
    <h3>Sick Note Stories</h3>
    {% for story in story_list2 %}
      <a href="{% url 'story_time:story_two' story.id %}">{{ story.story_name }}</a><br>
    {% endfor %}
  {% endif %}
  {% if story_list3 %}
    <h3>War Stories</h3>
    {% for story in story_list3 %}
      <a href="{% url 'story_time:story_war' story.id %}">{{ story.story_name }}</a><br>
    {% endfor %}
  {% endif %}
  {% if story_list4 %}
  <h3>Dragon Stories</h3>
    {% for story in story_list4 %}
      <a href="{% url 'story_time:story_dragons' story.id %}">{{ story.story_name }}</a><br>
    {% endfor %}
  {% endif %}
  {% if story_list5 %}
    <h3>The Walmart Difference Stories</h3>
    {% for story in story_list5 %}
      <a href="{% url 'story_time:story_walmart' story.id %}">{{ story.story_name }}</a><br>
    {% endfor %}
  {% endif %}
  {% if story_list6 %}
    <h3>Love Letter</h3>
    {% for story in story_list6 %}
      <a href="{% url 'story_time:story_love_letter' story.id %}">{{ story.story_name }}</a><br>
    {% endfor %}
  {% endif %}
  {% if story_list7 %}
    <h3>Smelly Cat</h3>
    {% for story in story_list7 %}
      <a href="{% url 'story_time:story_smelly_cat' story.id %}">{{ story.story_name }}</a><br>
    {% endfor %}
  {% endif %}
  {% if story_list8 %}
    <h3>Greeting Earthlings</h3>
    {% for story in story_list8 %}
      <a href="{% url 'story_time:story_greeting_earthlings' story.id %}">{{ story.story_name }}</a><br>
    {% endfor %}
  {% endif %}
  {% if story_list9 %}
    <h3>Hail To The Chief</h3>
    {% for story in story_list9 %}
      <a href="{% url 'story_time:story_hail_to_the_chief' story.id %}">{{ story.story_name }}</a><br>
    {% endfor %}
  {% endif %}
  {% if story_list10 %}
    <h3>Holiday Festivities</h3>
    {% for story in story_list10 %}
      <a href="{% url 'story_time:story_holiday_festivities' story.id %}">{{ story.story_name }}</a><br>
    {% endfor %}
  {% endif %}
  {% if story_list11 %}
    <h3>Pizza Parlor</h3>
    {% for story in story_list11 %}
      <a href="{% url 'story_time:story_pizza_parlor' story.id %}">{{ story.story_name }}</a><br>
      <br>
    {% endfor %}
  {% endif %}
  {% if story_list12 %}
    <h3>The Cat And The Fiddle</h3>
    {% for story in story_list12 %}
      <a href="{% url 'story_time:story_cat_and_the_fiddle' story.id %}">{{ story.story_name }}</a><br>
    {% endfor %}
  {% endif %}
  {% if story_list13 %}
    <h3>Baseball</h3>
    {% for story in story_list13 %}
      <a href="{% url 'story_time:story_baseball' story.id %}">{{ story.story_name }}</a><br>
    {% endfor %}
  {% endif %}
  {% if story_list14 %}
    <h3>J.J.R. Tolkien</h3>
    {% for story in story_list14 %}
      <a href="{% url 'story_time:story_JJRTolkien' story.id %}">{{ story.story_name }}</a><br>
    {% endfor %}
  {% endif %}
  {% if story_list15 %}
    <h3>J.J.R. Tolkien</h3>
    {% for story in story_list15 %}
      <a href="{% url 'story_time:story_jack_and_jill' story.id %}">{{ story.story_name }}</a><br>
    {% endfor %}
  {% endif %}
  </div>
{% endblock %}

story_time/templates/story_time/home.html
{% extends 'story_time/base.html' %}

{% block body %}
  <h2 class="text-center">Fun Stories</h2>
  <div class="container">
    <a href="{% url 'story_time:story_one_form' %}">Be Kind</a><br>
    <a href="{% url 'story_time:story_two_form' %}">Sick Note</a><br>
    <a href="{% url 'story_time:story_war_form' %}">War</a><br>
    <a href="{% url 'story_time:story_dragons_form' %}">Dragons</a><br>
    <a href="{% url 'story_time:story_walmart_form' %}">The Walmart Difference</a><br>
    <a href="{% url 'story_time:story_love_letter_form' %}">Love Letter</a><br>
    <a href="{% url 'story_time:story_smelly_cat_form' %}">Smelly Cat</a><br>
    <a href="{% url 'story_time:story_greeting_earthlings_form' %}">Greeting Earthlings</a></a><br>
    <a href="{% url 'story_time:story_hail_to_the_chief_form' %}">Hail To The Chief</a></a><br>
    <a href="{% url 'story_time:story_holiday_festivities_form' %}">Holiday Festivities</a></a><br>
    <a href="{% url 'story_time:story_pizza_parlor_form' %}">Pizza Parlor</a></a><br>
    <a href="{% url 'story_time:story_cat_and_the_fiddle_form' %}">The Cat And The Fiddle</a></a><br>
    <a href="{% url 'story_time:story_baseball_form' %}">Baseball</a></a><br>
    <a href="{% url 'story_time:story_JJRTolkien_form' %}">J.J.R Tolkien</a></a><br>
    <a href="{% url 'story_time:story_jack_and_jill_form' %}">Jack And Jill</a></a><br>
    <hr/>
  </div>
{% endblock %}

story_time/templates/story_time/story_baseball.html
{% extends 'story_time/base.html' %}

{% block body %}
<div class="container mt-3">
  <h3 class="text-center">Baseball</h3>
  <p class="text-center">
    {{ item.noun1 }} is a very exciting sport. Whether you are {{ item.verb1 }} the ball with a<br>
    {{ item.noun2 }}, or you are the {{ item.occupation }} and striking out {{ item.number }}batters in a<br>
    row, you`ll be having fun. You can also be the catcher, standing at {{ item.location }} plate,<br>
    ready to {{ item.verb2 }} the next person as he tries to make it {{ item.location }}. But the best part<br>
    of it is when someone hits a {{ item.adjective }} slam when all the {{ item.noun3 }} are loaded<br>
    during the last {{ item.noun4 }} to win the game.
  </p>
</div>
{% endblock %}

story_time/templates/story_time/story_cat_and_the_fiddle.html
{% extends 'story_time/base.html' %}

{% block body %}
<div class="container mt-3">
  <h3 class="text-center">Cat And The Fiddle</h3>
  <p class="text-center">Hey, {{ item.silly_word }}, {{ item.silly_word }}!<br>
    The {{ item.animal }} and the {{ item.musical_instrument }},<br>
    The cow jumped over the {{ item.noun1 }};<br>
    The {{ item.adjective1 }} dog laughed<br>
    To see such sport,<br>
    And the {{ item.noun2 }} ran away with the spoon.
  </p>
</div>
{% endblock %}

story_time/templates/story_time/story_dragons.html
{% extends 'story_time/base.html' %}

{% block body %}
<div class="container mt-3">
  <h3 class="text-center">Dragons</h3>
  <p class="text-center">The {{ item.color }} Dragon is the {{ item.superlative }} Dragon of it all. It has
    {{ item.adjective1 }} {{ item.body_part }}, and a<br>
    {{ item.body_part2 }} shaped like a {{ item.noun1 }}. It loves to eat {{ item.animal }}, although it will feast on <br>
    nearly anything. It is {{ item.adjective2 }} and {{ item.adjective3 }}. You must be {{ item.adjective4 }} around it, or you<br>
    may end up as it's meal!
  </p>
</div>
{% endblock %}

story_time/templates/story_time/story_form.html
{% extends 'story_time/base.html' %}

{% block body %}
  <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Generate Story</button>
  </form>
{% endblock %}

story_time/templates/story_time/story_greeting_earthlings.html
{% extends 'story_time/base.html' %}

{% block body %}
<div class="container mt-3">
  <h3 class="text-center">Greetings Earthlings</h3>
  <p class="text-center">In the book War of the {{ item.noun1 }}, them ain character is an anonymous<br>
    {{ item.occupation }} who records the arrival of {{ item.animal }} in {{ item.place }}.<br>
    Needless to say, havoc reigns as the {{ item.animal }} continue to {{ item.verb1 }}<br>
    everything in sight, until they are killed by the common {{ item.noun2 }}
  </p>
</div>
{% endblock %}

story_time/templates/story_time/story_hail_to_the_chief.html
{% extends 'story_time/base.html' %}

{% block body %}
<div class="container mt-3">
  <h3 class="text-center">Hail To The Chief</h3>
  <p class="text-center">The president of the {{ item.place }} is elected every {{ item.time }} by a group of people
    called the<br>
    {{ item.adjective1 }} College. Each {{ item.noun1 }} casts votes in a preliminary hearing called a {{ item.noun2 }}<br>
    Throughout the campaign, the candidates participate in {{ item.noun3 }} and {{ item.noun4 }}.<br>
    Many people try to {{ item.verb1 }} the outcome using polls and statistics. In the end, only<br>
    one person is selected to {{ item.verb2 }} the country as {{ item.occupation }} in Chief.
  </p>
</div>
{% endblock %}

story_time/templates/story_time/story_holiday_festivities.html
{% extends 'story_time/base.html' %}

{% block body %}
<div class="container mt-3">
  <h3 class="text-center">Holiday Festivities</h3>
  <p class="text-center">On {{ item.month }} {{ item.number }} every year, we celebrate {{ item.holiday }}.
    All the {{ item.noun1 }} and {{ item.verb1 }} up in<br>
    {{ item.noun2 }} and {{ item.verb2 }}all over the {{ item.noun3 }}. Many people love to ear their favorite<br>
    {{ item.noun4 }} or {{ item.noun5 }} much to their {{ item.occupation }} dismay.
  </p>
</div>
{% endblock %}

story_time/templates/story_time/story_jack_and_jill.html
{% extends 'story_time/base.html' %}

{% block body %}
<div class="container mt-3">
  <h3 class="text-center">Jack And Jil</h3>
  <p class="text-center">
    Jack and Jill went up the {{ item.noun1 }},<br>
    To {{ item.verb1 }} a pail of {{ item.liquid }};<br>
    Jack {{ item.verb2ing }} down, and broke his {{ item.noun2 }},<br>
    And Jill came {{ item.verb3ing }} after.<br><br>

    Then up Jack got and off did {{ item.verb4 }},<br>
    As {{ item.adjective1 }} as he could caper,<br>
    To old Dame Dob, who patched his {{ item.noun2 }}<br>
    With {{ item.noun3 }} and {{ item.adjective2 }} paper.

  </p>
</div>
{% endblock %}

story_time/templates/story_time/story_one.html
{% extends 'story_time/base.html' %}

{% block body %}
  <div class="text-center mt-3">
  <h3 class="text-center">Be Kind</h3>
  {{ storylist }}
    <p>Be kind to your {{ item.noun_one }}-footed {{ item.noun_two }}<br>
    For a duck may be somebody's {{ item.noun_three }}<br>
    Be kind to your {{ item.noun_two }} in {{ item.place }}<br>
    Where the weather is always {{ item.adjective }}<br><br>
    You may think that this is the {{ item.noun_four }}<br>
    Well it is.</p>
  </div>

{#<a href="{% url 'story_time:story_delete' %}" class=" full_button_margin btn btn-success">continue</a>#}
{% endblock %}

story_time/templates/story_time/story_smelly_cat.html
{% extends 'story_time/base.html' %}

{% block body %}
<div class="container mt-3">
  <h3 class="text-center">Smelly Cat</h3>
  <p class="text-center">Smelly {{ item.animal }}, smelly {{ item.animal }}<br>
    What are they {{ item.verb1 }} you?<br>
    Smelly {{ item.animal }}, smelly {{ item.animal }}<br>
    Its not your {{ item.noun1 }}<br><br>
    They won't {{ item.verb2 }} you to the {{ item.occupation }}.<br>
    You're obviously not their {{ item.adjective1 }} {{ item.animal2 }}.<br>
    You may not be a {{ item.noun2 }} of {{ item.noun3 }},<br>
    And your're no {{ item.relationship }} to those with {{ item.body_part }}.<br><br>
    Smelly {{ item.animal }}, smelly {{ item.animal }}<br>
    What are they {{ item.verb3 }}
    Smelly {{ item.animal }}, smelly {{ item.animal }}<br>
    It's not your {{ item.noun4 }}.
  </p>
</div>
{% endblock %}

story_time/templates/story_time/story_walmart.html
{% extends 'story_time/base.html' %}

{% block body %}
<div class="container mt-3">
  <h3 class="text-center">Walmart</h3>
  <p class="text-center">
    Come {{ item.verb1 }} at WALMART, where you'll receive {{ item.adjective1 }} discounts on all<br>
    of your favorite brand name {{ item.noun1 }}. Our {{ item.adjective2 }} and {{ item.verb2 }} associates are<br>
    there to {{ item.verb3 }} you {{ item.number }} hours a day. Here you will find {{ item.adjective3 }} prices<br>
    on the {{ item.noun2 }} you need. {{ item.noun3 }} for the mons, {{ item.noun4 }} for the kids and<br>
    all the latest electronics for the {{ item.relative }}. So come on down to your {{ item.adjective4 }}<br>
    {{ item.adjective5 }} WALMART where the {{ item.noun5 }} comes first.
  </p>
</div>
{% endblock %}

story_time/templates/story_time/story_war.html
{% extends 'story_time/base.html' %}

{% block body %}
<div class="container mt-3">
  <h3 class="text-center">War</h3>
  <p class="text-center">It was during the battle of {{ item.noun1 }} when I was running through a {{ item.noun2 }}
    when a<br>
    {{ item.noun3 }} went off right next to my platoon. Out {{ item.occupation }} yelled for us to<br>
    {{ item.verb }} to the nearest {{ item.place }} we could find. When we gor to the {{ item.place }} we <br>
    {{ item.verb2 }} to start a fire. As we were starting the fire the enemy saw the {{ item.noun4 }}<br>
    from the fire and started {{ item.verb3 }} {{ item.noun5 }} at us. We all quickly ducked behind<br>
    the {{ item.noun6 }} at the {{ item.place }} and returned fire. We quickly eliminated the eneby and<br>
    were {{ item.emotion }} that we had won the battle.
  </p>
</div>
{% endblock %}